version: "3.8"
services:
  app:
    build: .
    depends_on:
      - db
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    ports:
      - "5000:3000"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: root
      POSTGRES_DB: test_db
      POSTGRES_HOST: db
    ports:
      - "5432:5432"
